#
# SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
# SPDX-License-Identifier: Apache-2.0
#

[versions]
activity = "1.13.0"
agp = "9.4.1"
compat = "1.8.0"
composeBom = "2026.09.00"
core = "1.19.1"
kotlin = "2.4.21"
lifecycle = "2.11.0"
weblate = "+"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-compat = { module = "androidx.appcompat:appcompat", version.ref = "compat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
weblate-android = { module = "org.weblate:android", version.ref = "weblate" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
weblate-android = { id = "org.weblate.android", version.ref = "weblate" }
