#
# SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
# SPDX-License-Identifier: Apache-2.0
#

[versions]
# Version code for the plugin and library
weblate = "1.0.0-alpha02"

agp = "9.4.1"
annotations = "1.11.0"
coroutines = "1.11.0"
dokka = "2.2.0"
gradle = "2.2.1"
json = "20260814"
kotlin = "2.4.21"

[libraries]
android-gradle-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "annotations" }
json = { module = "org.json:json", version.ref = "json" }
jetbrains-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

[plugins]
android-library-core = { id = "com.android.library", version.ref = "agp" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle" }
jetbrains-dokka-html = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
