#
# SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
# SPDX-License-Identifier: GPL-3.0-or-later
#

[versions]
# Version code for the plugin and library
weblate = "1.0.0-alpha01"

agp = "9.4.1"
dokka = "2.2.0"
gradle = "2.2.1"
json = "20260814"
kotlin = "2.4.20"
work = "2.12.0"

[libraries]
android-gradle-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
androidx-work = { module = "androidx.work:work-runtime", version.ref = "work" }
json = { module = "org.json:json", version.ref = "json" }

[plugins]
android-library-core = { id = "com.android.library", version.ref = "agp" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle" }
jetbrains-dokka-html = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
