/*
 * SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.weblate.plugin.android

import java.io.File
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Task to generate a config class to access values supplied to extension by library
 * @see WeblateAndroidPluginExtension
 */
internal abstract class GenerateConfigTask : DefaultTask() {

    @get:Input
    abstract val cdnUrl: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val outputDir = outputDirectory.get().asFile
        val configClassPath = "org.weblate.android.ConfigProvider"
        val generatedClassName = "WeblateConfigProvider"
        val generatedPackageName = "org.weblate.android.generated"

        val serviceDir = File(outputDir, "META-INF/services").also { file ->
            file.mkdirs()
        }

        File(serviceDir, configClassPath)
            .writeText("${generatedPackageName}.${generatedClassName}")

        val packageFolder = File(outputDir, generatedPackageName.replace('.', '/')).also { file ->
            file.mkdirs()
        }

        val file = File(packageFolder, "$generatedClassName.kt")
        val content = """
            |package $generatedPackageName
            |
            |import $configClassPath
            |
            |/**
            | * Generated by the Weblate Gradle Plugin. Do not modify manually.
            | */
            |public class $generatedClassName : ConfigProvider {
            |    override val cdnUrl: String = "${cdnUrl.get()}"
            |}
        """.trimMargin()

        file.writeText(content)
    }
}
