/*
 * SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.weblate.plugin.android

import java.io.File
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Task to generate a config class to access values supplied to extension by library
 * @see WeblateAndroidPluginExtension
 */
internal abstract class GenerateConfigTask : DefaultTask() {

    @get:Input
    abstract val cdnUrl: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val outputDir = outputDirectory.get().asFile
        val packageName = "org.weblate.android.generated"
        val packageFolder = File(outputDir, packageName.replace('.', '/')).also { file ->
            file.mkdirs()
        }

        val file = File(packageFolder, "WeblateConfig.kt")
        val content = """
            |package $packageName
            |
            |/**
            | * Generated by the Weblate Gradle Plugin. Do not modify manually.
            | */
            |object WeblateConfig {
            |    const val CDN_URL: String = "${cdnUrl.get()}"
            |}
        """.trimMargin()

        file.writeText(content)
    }
}
