/*
 * SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.weblate.android

/**
 * Contract providing required configuration for library.
 *
 * The corresponding contract will auto-generated by the Gradle plugin as a service with values
 * supplied to the extension.
 */
public interface ConfigProvider {
    /**
     * URL of the CDN server
     */
    public val cdnUrl: String
}
