/*
 * SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.weblate.android.model

import kotlinx.serialization.Serializable

/**
 * Manifest generated by Weblate server
 */
@Serializable
public data class Manifest(
    val locales: Map<String, Artifact>,
    val packageName: String,
    val schemaVersion: Int,
    val versionCode: Long
)

@Serializable
public data class Artifact(
    val sha256: String,
    val size: Long,
    val url: String
)
